"""ViewSpec — Universal UI from semantic data."""

from viewspec.types import (
    ActionIntent,
    ASTBundle,
    BindingSpec,
    CompileRequestPayload,
    CompileResponse,
    CompileResponseMeta,
    CompilerDiagnostic,
    CompilerResult,
    CompositionIR,
    DesignFinding,
    DesignMetadata,
    DesignRequest,
    GroupSpec,
    IntentBundle,
    IRNode,
    MotifSpec,
    Provenance,
    RegionSpec,
    SemanticNode,
    SemanticSubstrate,
    StyleSpec,
    ViewSpec,
    build_address_index,
    normalize_compiler_result,
    parse_canonical_address,
    resolve_address,
)
from viewspec.sdk import (
    ComparisonBuilder,
    DashboardBuilder,
    OutlineBuilder,
    TableBuilder,
    ViewSpecBuilder,
)
from viewspec.compiler import (
    compile,
    compile_auto,
    compile_remote,
    compile_remote_response,
    CompilerAPIError,
    CompilerInputError,
    UnsupportedMotifError,
)
from viewspec.agent import (
    AGENT_INTENT_BUNDLE_SCHEMA,
    AGENT_SYSTEM_PROMPT,
    SUPPORTED_AGENT_MOTIFS,
    AgentValidationIssue,
    AgentValidationResult,
    agent_correction_prompt,
    validate_agent_intent_bundle,
)

__version__ = "0.1.0"

__all__ = [
    # Types
    "ActionIntent",
    "ASTBundle",
    "BindingSpec",
    "CompileRequestPayload",
    "CompileResponse",
    "CompileResponseMeta",
    "CompilerDiagnostic",
    "CompilerResult",
    "CompositionIR",
    "DesignFinding",
    "DesignMetadata",
    "DesignRequest",
    "GroupSpec",
    "IntentBundle",
    "IRNode",
    "MotifSpec",
    "Provenance",
    "RegionSpec",
    "SemanticNode",
    "SemanticSubstrate",
    "StyleSpec",
    "ViewSpec",
    # SDK Builders
    "ComparisonBuilder",
    "DashboardBuilder",
    "OutlineBuilder",
    "TableBuilder",
    "ViewSpecBuilder",
    # Compiler
    "compile",
    "compile_auto",
    "compile_remote",
    "compile_remote_response",
    "CompilerAPIError",
    "CompilerInputError",
    "UnsupportedMotifError",
    # Agent integration
    "AGENT_INTENT_BUNDLE_SCHEMA",
    "AGENT_SYSTEM_PROMPT",
    "SUPPORTED_AGENT_MOTIFS",
    "AgentValidationIssue",
    "AgentValidationResult",
    "agent_correction_prompt",
    "validate_agent_intent_bundle",
    # Utilities
    "build_address_index",
    "normalize_compiler_result",
    "parse_canonical_address",
    "resolve_address",
]
