"""ViewSpec — Universal UI from semantic data."""

from viewspec._version import __version__
from viewspec.types import (
    ActionIntent,
    ASTBundle,
    BindingSpec,
    CompileRequestPayload,
    CompileResponse,
    CompileResponseMeta,
    CompilerDiagnostic,
    CompilerResult,
    CompositionIR,
    DesignFinding,
    DesignMetadata,
    DesignRequest,
    GroupSpec,
    IntentBundle,
    IRNode,
    MotifSpec,
    Provenance,
    RegionSpec,
    SemanticNode,
    SemanticSubstrate,
    StyleSpec,
    ViewSpec,
    build_address_index,
    normalize_compiler_result,
    parse_canonical_address,
    resolve_address,
)
from viewspec.sdk import (
    ComparisonBuilder,
    DashboardBuilder,
    OutlineBuilder,
    TableBuilder,
    ViewSpecBuilder,
)
from viewspec.compiler import (
    compile,
    compile_auto,
    compile_remote,
    compile_remote_response,
    CompilerAPIError,
    CompilerInputError,
    UnsupportedMotifError,
)
from viewspec.design_md import (
    DesignLintFinding,
    DesignLintReport,
    DesignSystemContext,
    DesignSystemError,
    load_design_system,
)
from viewspec.raw_html import (
    HtmlCompileResult,
    HtmlInputError,
    HtmlLiftResult,
    HtmlRole,
    HtmlSemanticDiff,
    HtmlTopologyFingerprint,
    SANITIZER_POLICY,
    compile_html,
    diff_html,
    lift_html,
)
from viewspec.aesthetics import AESTHETIC_PROFILE_TOKENS, profile_style_facts
from viewspec.agent import (
    AGENT_INTENT_BUNDLE_SCHEMA,
    AGENT_SYSTEM_PROMPT,
    SUPPORTED_AGENT_ACTION_KINDS,
    SUPPORTED_AGENT_CARDINALITIES,
    SUPPORTED_AGENT_GROUP_KINDS,
    SUPPORTED_AGENT_MOTIFS,
    SUPPORTED_AGENT_REGION_LAYOUTS,
    SUPPORTED_AGENT_STYLE_TOKENS,
    AgentValidationIssue,
    AgentValidationResult,
    agent_correction_prompt,
    agent_repair_checklist,
    validate_agent_intent_bundle,
)
from viewspec.agent_assets import (
    AGENT_ASSET_MANIFEST_FILE,
    AGENT_ASSET_PAYLOAD_FILES,
    AGENT_ASSET_SCHEMA_VERSION,
    AGENT_INTENT_EXAMPLE_FILE,
    AGENT_INTENT_SCHEMA_FILE,
    AGENT_SYSTEM_PROMPT_FILE,
    agent_asset_readiness,
    check_agent_assets,
    export_agent_assets,
    plan_agent_asset_exports,
)
from viewspec.intent_tools import (
    STARTER_INTENT_KINDS,
    diff_intent_files,
    diff_intent_text,
    init_intent_file,
    intent_semantic_change_lines,
    starter_intent_bundle,
    validate_intent_file,
    validate_intent_text,
)
from viewspec.manifest_summary import (
    manifest_aesthetic_layout_summary,
    manifest_aesthetic_style_summary,
    manifest_root_aesthetic_profile,
    summarize_intent_manifest,
)
from viewspec.host_verify import (
    summarize_host_verification_report,
    verify_host_artifact_dir,
    verify_host_intent_file,
    verify_host_tool,
)
from viewspec.prove import prove, prove_tool

__all__ = [
    "__version__",
    # Types
    "ActionIntent",
    "ASTBundle",
    "BindingSpec",
    "CompileRequestPayload",
    "CompileResponse",
    "CompileResponseMeta",
    "CompilerDiagnostic",
    "CompilerResult",
    "CompositionIR",
    "DesignFinding",
    "DesignMetadata",
    "DesignRequest",
    "GroupSpec",
    "IntentBundle",
    "IRNode",
    "MotifSpec",
    "Provenance",
    "RegionSpec",
    "SemanticNode",
    "SemanticSubstrate",
    "StyleSpec",
    "ViewSpec",
    # SDK Builders
    "ComparisonBuilder",
    "DashboardBuilder",
    "OutlineBuilder",
    "TableBuilder",
    "ViewSpecBuilder",
    # Compiler
    "compile",
    "compile_auto",
    "compile_remote",
    "compile_remote_response",
    "CompilerAPIError",
    "CompilerInputError",
    "UnsupportedMotifError",
    # Local DESIGN.md
    "DesignLintFinding",
    "DesignLintReport",
    "DesignSystemContext",
    "DesignSystemError",
    "load_design_system",
    # Raw HTML pipeline
    "HtmlCompileResult",
    "HtmlInputError",
    "HtmlLiftResult",
    "HtmlRole",
    "HtmlSemanticDiff",
    "HtmlTopologyFingerprint",
    "SANITIZER_POLICY",
    "compile_html",
    "diff_html",
    "lift_html",
    # Aesthetic profiles
    "AESTHETIC_PROFILE_TOKENS",
    "profile_style_facts",
    # Agent integration
    "AGENT_INTENT_BUNDLE_SCHEMA",
    "AGENT_SYSTEM_PROMPT",
    "AGENT_ASSET_MANIFEST_FILE",
    "AGENT_ASSET_PAYLOAD_FILES",
    "AGENT_ASSET_SCHEMA_VERSION",
    "AGENT_INTENT_EXAMPLE_FILE",
    "AGENT_INTENT_SCHEMA_FILE",
    "AGENT_SYSTEM_PROMPT_FILE",
    "SUPPORTED_AGENT_ACTION_KINDS",
    "SUPPORTED_AGENT_CARDINALITIES",
    "SUPPORTED_AGENT_GROUP_KINDS",
    "SUPPORTED_AGENT_MOTIFS",
    "SUPPORTED_AGENT_REGION_LAYOUTS",
    "SUPPORTED_AGENT_STYLE_TOKENS",
    "AgentValidationIssue",
    "AgentValidationResult",
    "agent_correction_prompt",
    "agent_repair_checklist",
    "agent_asset_readiness",
    "check_agent_assets",
    "export_agent_assets",
    "plan_agent_asset_exports",
    "validate_agent_intent_bundle",
    "STARTER_INTENT_KINDS",
    "diff_intent_files",
    "diff_intent_text",
    "intent_semantic_change_lines",
    "init_intent_file",
    "starter_intent_bundle",
    "validate_intent_file",
    "validate_intent_text",
    "manifest_aesthetic_layout_summary",
    "manifest_aesthetic_style_summary",
    "manifest_root_aesthetic_profile",
    "summarize_intent_manifest",
    "summarize_host_verification_report",
    "verify_host_artifact_dir",
    "verify_host_intent_file",
    "verify_host_tool",
    "prove",
    "prove_tool",
    # Utilities
    "build_address_index",
    "normalize_compiler_result",
    "parse_canonical_address",
    "resolve_address",
]
