"""Generate the bounded browser-side Pretext native-DOM probe.

The generated module is intentionally isolated from the React renderer.  It reads only
compiler-declared element ids, never replaces or mutates native DOM text, and exposes a
small browser proof protocol for the generated Playwright harness.
"""

from __future__ import annotations


PRETEXT_RUNTIME_PATH = "src/viewspec_pretext.ts"


_PRETEXT_RUNTIME_TYPESCRIPT = r"""// Generated by ViewSpec Pretext native DOM runtime v1. Do not edit.
import { prepare, layout, type PreparedText } from "@chenglou/pretext";
import { setLocale } from "@chenglou/pretext";

const PROFILE = "viewspec_pretext_native_dom_v1" as const;
const PROTOCOL = "viewspec.pretext-runtime-v1" as const;
const ENGINE = Object.freeze({
  name: "pretext" as const,
  package: "@chenglou/pretext" as const,
  version: "0.0.8" as const,
});

const MAX_SURFACES = 512;
const MAX_ID_LENGTH = 160;
const MAX_TEXT_BYTES = 16 * 1024;
const MAX_TOTAL_TEXT_BYTES = 256 * 1024;
const MAX_CACHE_ENTRIES = 16_384;
const FONT_READY_TIMEOUT_MS = 5_000;
const LINE_TOP_EPSILON_PX = 0.5;
const OVERFLOW_EPSILON_PX = 1;
const CHROMIUM_ARIAL_LAYOUT_FIT_TOLERANCE_PX = 1;
const SAFE_ID_RE = /^[A-Za-z0-9][A-Za-z0-9_.:-]*$/;
const LOCALE_RE = /^[A-Za-z0-9][A-Za-z0-9_.-]*$/;
const PX_RE = /^-?(?:[0-9]+(?:\.[0-9]+)?|\.[0-9]+)px$/;
const EMPTY_SHA256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
const CLIPPING_OVERFLOW_VALUES = new Set(["hidden", "clip"]);
const UNSAFE_SYSTEM_FAMILIES = new Set([
  "-apple-system",
  "blinkmacsystemfont",
  "system-ui",
  "ui-sans-serif",
  "ui-serif",
  "ui-monospace",
  "ui-rounded",
]);
const SUPPORTED_FONT_FAMILY = "arial";
const GENERIC_FONT_FAMILIES = new Set([
  "serif",
  "sans-serif",
  "monospace",
  "cursive",
  "fantasy",
  "math",
  "fangsong",
]);

type ProbeStatus = "passed" | "hidden" | "unsupported" | "failed";
type ProbeReason =
  | "input_invalid"
  | "input_limit_exceeded"
  | "duplicate_surface_id"
  | "runtime_document_fonts_unavailable"
  | "runtime_fonts_ready_failed"
  | "runtime_intl_segmenter_unavailable"
  | "runtime_canvas_2d_unavailable"
  | "runtime_crypto_subtle_unavailable"
  | "runtime_range_unavailable"
  | "target_missing"
  | "target_not_html_element"
  | "target_ir_mismatch"
  | "target_hidden"
  | "target_text_limit_exceeded"
  | "total_text_limit_exceeded"
  | "nested_text_content"
  | "generated_text_content"
  | "unsupported_locale"
  | "unsupported_text_transform"
  | "unsupported_writing_mode"
  | "unsupported_white_space"
  | "unsupported_word_break"
  | "unsupported_overflow_wrap"
  | "unsupported_letter_spacing"
  | "unsupported_line_height"
  | "unsupported_font_size"
  | "unsupported_font_features"
  | "unsupported_font_family"
  | "unsafe_system_font"
  | "named_font_not_loaded"
  | "content_box_width_invalid"
  | "line_count_mismatch"
  | "horizontal_overflow"
  | "vertical_overflow"
  | "internal_error";

export type ViewSpecPretextSurface = Readonly<{
  surface_id: string;
  ir_id: string;
}>;

export type ViewSpecPretextProbeInput = Readonly<{
  screenId: string;
  routeId: string;
  viewportId: string;
  surfaces: readonly ViewSpecPretextSurface[];
}>;

type ProbeEnvironment = Readonly<{
  browser: "chromium";
  locale: string;
  device_scale_factor: number;
  font_status: "loaded" | "failed" | "unsupported";
}>;

type ProbeCache = Readonly<{
  prepare_calls: number;
  unique_inputs: number;
  layout_calls: number;
  cache_hits: number;
}>;

type ProbeItem = {
  screen_id: string;
  route_id: string;
  viewport_id: string;
  surface_id: string;
  ir_id: string;
  status: ProbeStatus;
  input_sha256: string;
  input_bytes: number;
  reason?: ProbeReason;
  available_width?: number;
  line_height?: number;
  predicted_line_count?: number;
  observed_line_count?: number;
  horizontal_overflow?: boolean;
  vertical_overflow?: boolean;
};

export type ViewSpecPretextProbeReport = {
  engine: typeof ENGINE;
  environment: ProbeEnvironment;
  cache: ProbeCache;
  items: ProbeItem[];
  errors: Array<Readonly<{ surface_id: string | null; reason: ProbeReason }>>;
};

type StyleConfig = Readonly<{
  font: string;
  whiteSpace: "normal" | "pre-wrap";
  wordBreak: "normal" | "keep-all";
  overflowWrap: "anywhere";
  letterSpacing: number;
  lineHeight: number;
  lineHeightSource: "px" | "normal-1.2x-font-size";
}>;

type StyleResult =
  | Readonly<{ ok: true; config: StyleConfig }>
  | Readonly<{ ok: false; reason: ProbeReason }>;

const preparedCache = new Map<string, PreparedText>();
let prepareCalls = 0;
let layoutCalls = 0;
let cacheHits = 0;

function cacheReport(): ProbeCache {
  return {
    prepare_calls: prepareCalls,
    unique_inputs: preparedCache.size,
    layout_calls: layoutCalls,
    cache_hits: cacheHits,
  };
}

function hasCanvas2d(): boolean {
  try {
    return document.createElement("canvas").getContext("2d") !== null;
  } catch {
    return false;
  }
}

function environmentReport(fontStatus: ProbeEnvironment["font_status"]): ProbeEnvironment {
  const devicePixelRatio = Number.isFinite(window.devicePixelRatio) && window.devicePixelRatio > 0
    ? window.devicePixelRatio
    : 1;
  const candidateLocale = document.documentElement.lang || navigator.language || "en-US";
  const locale = candidateLocale.length <= 64 && LOCALE_RE.test(candidateLocale) ? candidateLocale : "en-US";
  return {
    browser: "chromium",
    locale,
    device_scale_factor: devicePixelRatio,
    font_status: fontStatus,
  };
}

function runtimeUnsupportedReason(): ProbeReason | null {
  if (typeof document.fonts?.ready?.then !== "function") return "runtime_document_fonts_unavailable";
  if (typeof Intl.Segmenter !== "function") return "runtime_intl_segmenter_unavailable";
  if (!hasCanvas2d()) return "runtime_canvas_2d_unavailable";
  if (typeof globalThis.crypto?.subtle?.digest !== "function") return "runtime_crypto_subtle_unavailable";
  if (typeof document.createRange !== "function") return "runtime_range_unavailable";
  return null;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isSafeId(value: unknown): value is string {
  return typeof value === "string"
    && value.length > 0
    && value.length <= MAX_ID_LENGTH
    && SAFE_ID_RE.test(value);
}

function validateInput(value: unknown):
  | Readonly<{ ok: true; input: ViewSpecPretextProbeInput }>
  | Readonly<{ ok: false; reason: ProbeReason }> {
  if (!isRecord(value)) return { ok: false, reason: "input_invalid" };
  if (!isSafeId(value.screenId) || !isSafeId(value.routeId) || !isSafeId(value.viewportId)) {
    return { ok: false, reason: "input_invalid" };
  }
  if (!Array.isArray(value.surfaces) || value.surfaces.length === 0 || value.surfaces.length > MAX_SURFACES) {
    return { ok: false, reason: "input_limit_exceeded" };
  }
  const seen = new Set<string>();
  const surfaces: ViewSpecPretextSurface[] = [];
  for (const candidate of value.surfaces) {
    if (!isRecord(candidate) || !isSafeId(candidate.surface_id) || !isSafeId(candidate.ir_id)) {
      return { ok: false, reason: "input_invalid" };
    }
    if (seen.has(candidate.surface_id)) return { ok: false, reason: "duplicate_surface_id" };
    seen.add(candidate.surface_id);
    surfaces.push({ surface_id: candidate.surface_id, ir_id: candidate.ir_id });
  }
  return {
    ok: true,
    input: {
      screenId: value.screenId,
      routeId: value.routeId,
      viewportId: value.viewportId,
      surfaces,
    },
  };
}

function statusItem(
  input: ViewSpecPretextProbeInput,
  surface: ViewSpecPretextSurface,
  status: "hidden" | "unsupported" | "failed",
  reason: ProbeReason,
  inputSha256 = EMPTY_SHA256,
  inputBytes = 0,
): ProbeItem {
  const item: ProbeItem = {
    screen_id: input.screenId,
    route_id: input.routeId,
    viewport_id: input.viewportId,
    surface_id: surface.surface_id,
    ir_id: surface.ir_id,
    status,
    input_sha256: inputSha256,
    input_bytes: inputBytes,
  };
  if (status !== "hidden") item.reason = reason;
  return item;
}

function parsePx(value: string): number | null {
  const normalized = value.trim().toLowerCase();
  if (!PX_RE.test(normalized)) return null;
  const parsed = Number.parseFloat(normalized.slice(0, -2));
  return Number.isFinite(parsed) ? parsed : null;
}

function splitFontFamilies(value: string): string[] {
  const families: string[] = [];
  let current = "";
  let quote = "";
  for (let index = 0; index < value.length; index += 1) {
    const character = value[index]!;
    if ((character === "\"" || character === "'") && (quote === "" || quote === character)) {
      quote = quote === "" ? character : "";
      current += character;
      continue;
    }
    if (character === "," && quote === "") {
      if (current.trim()) families.push(current.trim());
      current = "";
      continue;
    }
    current += character;
  }
  if (current.trim()) families.push(current.trim());
  return families;
}

function unquoteFontFamily(value: string): string {
  const trimmed = value.trim();
  if (trimmed.length >= 2) {
    const first = trimmed[0];
    const last = trimmed[trimmed.length - 1];
    if ((first === "\"" && last === "\"") || (first === "'" && last === "'")) {
      return trimmed.slice(1, -1);
    }
  }
  return trimmed;
}

function quoteFontFamily(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"")}"`;
}

function hasGeneratedText(element: HTMLElement, pseudo: "::before" | "::after"): boolean {
  const content = window.getComputedStyle(element, pseudo).content.trim();
  return content !== "" && content !== "none" && content !== "normal" && content !== "\"\"";
}

function firstGrapheme(value: string, locale: string | undefined): string {
  const segmenter = new Intl.Segmenter(locale, { granularity: "grapheme" });
  const first = segmenter.segment(value)[Symbol.iterator]().next();
  return first.done ? "" : first.value.segment;
}

function capitalizeText(value: string, locale: string | undefined): string {
  const segmenter = new Intl.Segmenter(locale, { granularity: "word" });
  let result = "";
  for (const part of segmenter.segment(value)) {
    if (!part.isWordLike) {
      result += part.segment;
      continue;
    }
    const first = firstGrapheme(part.segment, locale);
    result += first.toLocaleUpperCase(locale) + part.segment.slice(first.length);
  }
  return result;
}

function transformText(value: string, transform: string, locale: string | undefined): string | null {
  switch (transform) {
    case "none":
      return value;
    case "uppercase":
      return value.toLocaleUpperCase(locale);
    case "lowercase":
      return value.toLocaleLowerCase(locale);
    case "capitalize":
      return capitalizeText(value, locale);
    default:
      return null;
  }
}

function isAnywhereBoundary(value: string): boolean {
  return /\s/u.test(value) || value === "\u200b" || value === "\u00ad";
}

function addAnywhereBreakOpportunities(value: string, locale: string | undefined): string {
  const graphemes = Array.from(
    new Intl.Segmenter(locale, { granularity: "grapheme" }).segment(value),
    (part) => part.segment,
  );
  let result = "";
  for (let index = 0; index < graphemes.length; index += 1) {
    const current = graphemes[index]!;
    const previous = index > 0 ? graphemes[index - 1]! : null;
    if (previous !== null && !isAnywhereBoundary(previous) && !isAnywhereBoundary(current)) {
      result += "\u200b";
    }
    result += current;
  }
  return result;
}

function styleConfigFor(element: HTMLElement, style: CSSStyleDeclaration, transformedText: string): StyleResult {
  if (style.writingMode !== "horizontal-tb") {
    return { ok: false, reason: "unsupported_writing_mode" };
  }
  if (style.whiteSpace !== "normal" && style.whiteSpace !== "pre-wrap") {
    return { ok: false, reason: "unsupported_white_space" };
  }
  if (style.wordBreak !== "normal" && style.wordBreak !== "keep-all") {
    return { ok: false, reason: "unsupported_word_break" };
  }
  if (style.overflowWrap !== "anywhere") {
    return { ok: false, reason: "unsupported_overflow_wrap" };
  }

  let letterSpacing = 0;
  if (style.letterSpacing !== "normal") {
    const parsedLetterSpacing = parsePx(style.letterSpacing);
    if (parsedLetterSpacing === null || Math.abs(parsedLetterSpacing) > 256) {
      return { ok: false, reason: "unsupported_letter_spacing" };
    }
    letterSpacing = parsedLetterSpacing;
  }

  const fontSize = parsePx(style.fontSize);
  if (fontSize === null || fontSize <= 0 || fontSize > 512) {
    return { ok: false, reason: "unsupported_font_size" };
  }
  let lineHeight: number;
  let lineHeightSource: "px" | "normal-1.2x-font-size";
  if (style.lineHeight === "normal") {
    lineHeight = fontSize * 1.2;
    lineHeightSource = "normal-1.2x-font-size";
  } else {
    const parsedLineHeight = parsePx(style.lineHeight);
    if (parsedLineHeight === null || parsedLineHeight <= 0 || parsedLineHeight > 4096) {
      return { ok: false, reason: "unsupported_line_height" };
    }
    lineHeight = parsedLineHeight;
    lineHeightSource = "px";
  }

  if (
    (style.fontFeatureSettings && style.fontFeatureSettings !== "normal")
    || (style.fontVariationSettings && style.fontVariationSettings !== "normal")
    || (style.fontStretch && style.fontStretch !== "normal" && style.fontStretch !== "100%")
  ) {
    return { ok: false, reason: "unsupported_font_features" };
  }

  const families = splitFontFamilies(style.fontFamily);
  if (families.length === 0) return { ok: false, reason: "unsupported_font_family" };
  const firstFamily = unquoteFontFamily(families[0]!);
  if (UNSAFE_SYSTEM_FAMILIES.has(firstFamily.toLowerCase())) {
    return { ok: false, reason: "unsafe_system_font" };
  }
  if (
    !firstFamily
    || GENERIC_FONT_FAMILIES.has(firstFamily.toLowerCase())
    || firstFamily.toLowerCase() !== SUPPORTED_FONT_FAMILY
  ) {
    return { ok: false, reason: "unsupported_font_family" };
  }

  const font = `${style.fontStyle} ${style.fontWeight} ${fontSize}px ${quoteFontFamily(firstFamily)}`;
  try {
    if (!document.fonts.check(font, transformedText || " ")) {
      return { ok: false, reason: "named_font_not_loaded" };
    }
  } catch {
    return { ok: false, reason: "named_font_not_loaded" };
  }

  return {
    ok: true,
    config: {
      font,
      whiteSpace: style.whiteSpace,
      wordBreak: style.wordBreak,
      overflowWrap: style.overflowWrap,
      letterSpacing,
      lineHeight,
      lineHeightSource,
    },
  };
}

async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digestInput = new Uint8Array(bytes).buffer;
  const digest = new Uint8Array(await globalThis.crypto.subtle.digest("SHA-256", digestInput));
  return Array.from(digest, (value) => value.toString(16).padStart(2, "0")).join("");
}

async function sha256String(value: string): Promise<string> {
  return sha256Hex(new TextEncoder().encode(value));
}

function preparedFor(
  key: string,
  text: string,
  config: StyleConfig,
  locale: string,
): PreparedText | null {
  const cached = preparedCache.get(key);
  if (cached !== undefined) {
    cacheHits += 1;
    return cached;
  }
  if (preparedCache.size >= MAX_CACHE_ENTRIES) return null;
  setLocale(locale);
  const prepared = prepare(text, config.font, {
    whiteSpace: config.whiteSpace,
    wordBreak: config.wordBreak,
    letterSpacing: config.letterSpacing,
  });
  preparedCache.set(key, prepared);
  prepareCalls += 1;
  return prepared;
}

function observedLineTops(element: HTMLElement): number[] {
  const range = document.createRange();
  range.selectNodeContents(element);
  const tops = Array.from(range.getClientRects())
    .filter((rect) => Number.isFinite(rect.top) && Number.isFinite(rect.height) && rect.height > 0)
    .map((rect) => rect.top)
    .sort((left, right) => left - right);
  range.detach();
  const unique: number[] = [];
  for (const top of tops) {
    const previous = unique.length > 0 ? unique[unique.length - 1]! : null;
    if (previous === null || Math.abs(top - previous) > LINE_TOP_EPSILON_PX) {
      unique.push(Number(top.toFixed(3)));
    }
  }
  return unique;
}

function contentBoxWidth(element: HTMLElement, style: CSSStyleDeclaration): number | null {
  const paddingLeft = parsePx(style.paddingLeft);
  const paddingRight = parsePx(style.paddingRight);
  const borderLeft = parsePx(style.borderLeftWidth);
  const borderRight = parsePx(style.borderRightWidth);
  if (paddingLeft === null || paddingRight === null || borderLeft === null || borderRight === null) return null;
  const borderBoxWidth = element.getBoundingClientRect().width;
  const scrollbarWidth = Math.max(0, element.offsetWidth - element.clientWidth - borderLeft - borderRight);
  const width = borderBoxWidth - borderLeft - borderRight - paddingLeft - paddingRight - scrollbarWidth;
  return Number.isFinite(width) && width > 0 && width <= 100_000 ? width : null;
}

function isHidden(element: HTMLElement, style: CSSStyleDeclaration): boolean {
  return element.hidden !== false
    || style.display === "none"
    || style.visibility === "hidden"
    || style.visibility === "collapse"
    || element.getClientRects().length === 0;
}

function boundedLocale(value: string): string | null {
  return value.length > 0 && value.length <= 64 && LOCALE_RE.test(value) ? value : null;
}

async function preliminaryDigest(transformedText: string, locale: string): Promise<string> {
  return sha256String(JSON.stringify([transformedText, locale]));
}

async function probeItem(
  input: ViewSpecPretextProbeInput,
  surface: ViewSpecPretextSurface,
  totalBytes: { value: number },
  reportLocale: string,
): Promise<ProbeItem> {
  const target = document.getElementById(surface.surface_id);
  if (target === null) return statusItem(input, surface, "failed", "target_missing");
  if (!(target instanceof HTMLElement)) return statusItem(input, surface, "failed", "target_not_html_element");
  if (target.getAttribute("data-ir-id") !== surface.ir_id) {
    return statusItem(input, surface, "failed", "target_ir_mismatch");
  }

  const style = window.getComputedStyle(target);
  const locale = boundedLocale(target.lang || document.documentElement.lang || reportLocale);
  if (locale === null) return statusItem(input, surface, "unsupported", "unsupported_locale");
  const transformedText = transformText(target.textContent ?? "", style.textTransform, locale);
  if (transformedText === null) {
    return statusItem(input, surface, "unsupported", "unsupported_text_transform");
  }
  const textBytes = new TextEncoder().encode(transformedText);
  if (textBytes.byteLength > MAX_TEXT_BYTES) {
    return statusItem(input, surface, "failed", "target_text_limit_exceeded");
  }
  totalBytes.value += textBytes.byteLength;
  if (totalBytes.value > MAX_TOTAL_TEXT_BYTES) {
    return statusItem(input, surface, "failed", "total_text_limit_exceeded");
  }
  const earlyDigest = await preliminaryDigest(transformedText, locale);

  if (isHidden(target, style) || transformedText.length === 0) {
    return statusItem(input, surface, "hidden", "target_hidden", earlyDigest, textBytes.byteLength);
  }
  if (target.childElementCount !== 0) {
    return statusItem(input, surface, "unsupported", "nested_text_content", earlyDigest, textBytes.byteLength);
  }
  if (hasGeneratedText(target, "::before") || hasGeneratedText(target, "::after")) {
    return statusItem(input, surface, "unsupported", "generated_text_content", earlyDigest, textBytes.byteLength);
  }

  const styleResult = styleConfigFor(target, style, transformedText);
  if (!styleResult.ok) {
    return statusItem(input, surface, "unsupported", styleResult.reason, earlyDigest, textBytes.byteLength);
  }
  const config = styleResult.config;
  const measurementText = addAnywhereBreakOpportunities(transformedText, locale);
  const cacheKey = JSON.stringify([
    measurementText,
    config.font,
    config.whiteSpace,
    config.wordBreak,
    config.letterSpacing,
    locale,
  ]);
  const inputSha256 = await sha256String(cacheKey);
  const width = contentBoxWidth(target, style);
  if (width === null) {
    return statusItem(input, surface, "failed", "content_box_width_invalid", inputSha256, textBytes.byteLength);
  }

  const prepared = preparedFor(cacheKey, measurementText, config, locale);
  if (prepared === null) {
    return statusItem(input, surface, "unsupported", "input_limit_exceeded", inputSha256, textBytes.byteLength);
  }
  const predicted = layout(prepared, width + CHROMIUM_ARIAL_LAYOUT_FIT_TOLERANCE_PX, config.lineHeight);
  layoutCalls += 1;
  const lineTops = observedLineTops(target);
  const horizontalOverflow = target.scrollWidth > target.clientWidth + OVERFLOW_EPSILON_PX;
  const verticalOverflow = target.scrollHeight > target.clientHeight + OVERFLOW_EPSILON_PX;
  const horizontalClipped = horizontalOverflow && CLIPPING_OVERFLOW_VALUES.has(style.overflowX);
  const verticalClipped = verticalOverflow && CLIPPING_OVERFLOW_VALUES.has(style.overflowY);

  let reason: ProbeReason | null = null;
  if (predicted.lineCount !== lineTops.length) reason = "line_count_mismatch";
  else if (horizontalOverflow || horizontalClipped) reason = "horizontal_overflow";
  else if (verticalOverflow || verticalClipped) reason = "vertical_overflow";

  const metrics = {
    available_width: Number(width.toFixed(6)),
    line_height: Number(config.lineHeight.toFixed(6)),
    predicted_line_count: predicted.lineCount,
    observed_line_count: lineTops.length,
    horizontal_overflow: horizontalOverflow,
    vertical_overflow: verticalOverflow,
  };
  if (reason !== null) {
    return {
      ...statusItem(input, surface, "failed", reason, inputSha256, textBytes.byteLength),
      ...metrics,
    };
  }
  return {
    screen_id: input.screenId,
    route_id: input.routeId,
    viewport_id: input.viewportId,
    surface_id: surface.surface_id,
    ir_id: surface.ir_id,
    input_sha256: inputSha256,
    input_bytes: textBytes.byteLength,
    status: "passed",
    ...metrics,
  };
}

function errorsFor(items: readonly ProbeItem[]): ViewSpecPretextProbeReport["errors"] {
  return items
    .filter((item) => item.status === "failed" || item.status === "unsupported")
    .map((item) => ({ surface_id: item.surface_id, reason: item.reason ?? "internal_error" }));
}

function report(environment: ProbeEnvironment, items: ProbeItem[]): ViewSpecPretextProbeReport {
  return {
    engine: ENGINE,
    environment,
    cache: cacheReport(),
    items,
    errors: errorsFor(items),
  };
}

async function waitForFonts(): Promise<boolean> {
  let timeoutId = 0;
  try {
    await Promise.race([
      document.fonts.ready,
      new Promise<never>((_resolve, reject) => {
        timeoutId = window.setTimeout(() => reject(new Error("font timeout")), FONT_READY_TIMEOUT_MS);
      }),
    ]);
    return true;
  } catch {
    return false;
  } finally {
    if (timeoutId !== 0) window.clearTimeout(timeoutId);
  }
}

export async function probe(inputValue: ViewSpecPretextProbeInput): Promise<ViewSpecPretextProbeReport> {
  const validation = validateInput(inputValue);
  if (!validation.ok) {
    return {
      engine: ENGINE,
      environment: environmentReport("unsupported"),
      cache: cacheReport(),
      items: [],
      errors: [{ surface_id: null, reason: validation.reason }],
    };
  }
  const input = validation.input;
  const runtimeReason = runtimeUnsupportedReason();
  if (runtimeReason !== null) {
    const items = input.surfaces.map((surface) => statusItem(input, surface, "unsupported", runtimeReason));
    return report(environmentReport("unsupported"), items);
  }
  if (!(await waitForFonts())) {
    const reason: ProbeReason = "runtime_fonts_ready_failed";
    const items = input.surfaces.map((surface) => statusItem(input, surface, "unsupported", reason));
    return report(environmentReport("failed"), items);
  }

  const environment = environmentReport("loaded");
  const totalBytes = { value: 0 };
  const items: ProbeItem[] = [];
  for (const surface of input.surfaces) {
    try {
      items.push(await probeItem(input, surface, totalBytes, environment.locale));
    } catch {
      items.push(statusItem(input, surface, "failed", "internal_error"));
    }
  }
  return report(environment, items);
}

declare global {
  interface Window {
    __viewspecPretextProbe?: typeof probe;
  }
}

export function installViewSpecPretextProbe(): void {
  if (typeof window !== "undefined") window.__viewspecPretextProbe = probe;
}
"""


def generate_pretext_runtime_typescript() -> str:
    """Return the deterministic generated TypeScript browser runtime."""

    return _PRETEXT_RUNTIME_TYPESCRIPT


__all__ = ["PRETEXT_RUNTIME_PATH", "generate_pretext_runtime_typescript"]
